title: "Your Name — Teaching"
description: "Lectures, slides, exercises, and academic achievements"
url: ""  # set to https://<your-username>.github.io/<repo-name> after publishing
baseurl: "" # leave empty if deploying at the repo root

# Minimal Mistakes settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 5
paginate_path: "/blog/page:num"

# Author
author:
  name: "Your Name"
  avatar: "/assets/img/avatar.jpg"   # replace if desired
  bio: "Lecturer & researcher. I share my course materials here."
  location: "Netherlands"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:your.email@example.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/YOUR-USERNAME"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/YOUR-LINK/"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/YOUR-ORCID"

# Navigation
collections: 
  posts:
    output: true
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      read_time: true
      share: true
      comments: false
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true

# Excerpts on index
excerpt_separator: "<!--more-->"

# Permalinks
permalink: /:categories/:title/
