title: "Timmy Paez Watson — Teaching"
description: "Lectures, slides, exercises, and academic achievements"
url: "https://tp-watson.github.io"
baseurl: "/Teaching-Site" # repo name here, because it's not at root

# Minimal Mistakes settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 5
paginate_path: "/blog/page:num"

# Author
author:
  name: "Timmy Paez Watson"
  avatar: "{{ site.baseurl }}/assets/img/avatar.jpg"   
  bio: "Teacher, PhD in Environmental Biotechnology. I teach metabolic networks and modelling."
  location: "Netherlands"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:timothypaezw@gmail.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/tp-watson"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/timothy-p%C3%A1ez-watson-269968159/"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0000-0001-6103-0375"

# Navigation
collections: 
  posts:
    output: true
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      read_time: true
      share: true
      comments: false
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true

# Excerpts on index
excerpt_separator: "<!--more-->"

# Permalinks
permalink: /:categories/:title/
